services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mediaindordb
      POSTGRES_USER: renan
      POSTGRES_PASSWORD: ccaf
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: